tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# set arguments for all 'brew install --cask' commands
cask_args appdir: "/Applications"

# 'brew install'
brew "autoconf"
brew "autossh"
brew "ca-certificates"
brew "gdbm"
brew "gettext"
brew "libffi"
brew "pcre"
brew "openssl@3"
brew "readline"
brew "sqlite"
brew "xz"
brew "glib"
brew "pixman"
brew "pkg-config"
brew "cairo"
brew "cmake"
brew "libssh2"
brew "curl", args: ["with-libssh2"]
brew "libsodium"
brew "zeromq"
brew "czmq"
brew "gobject-introspection"
brew "icu4c"
brew "harfbuzz"
brew "jpeg"
brew "libtiff"
brew "libtool"
brew "pango"
brew "fontforge"
brew "jbig2dec"
brew "little-cms2"
brew "ghostscript"
brew "git"
brew "git-ftp"
brew "hugo"
brew "imagemagick"
brew "libevent"
brew "libyaml"
brew "lua"
brew "mas"
brew "macvim"
brew "pandoc"
brew "python"
brew "reattach-to-user-namespace"
brew "terminal-notifier"
brew "tig"
brew "tmux"
brew "wget"
brew "xpdf"
brew "zsh"

# 'brew install --cask'
cask "adobe-digital-editions"
cask "alfred"
cask "authy"
cask "brave-browser"
cask "calibre"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "mactex"
cask "obs"
cask "skim"
cask "spotify"
cask "todoist"
cask "toggl-track"
cask "vlc"
cask "webex-meetings"
cask "zoom"
cask "zotero"

# 'mas install'
mas "RunCat", id: 1429033973
mas "Sensible Paster", id: 1553906835
